package com.reyzarium.eventforge.paymentservice.common.error;

public enum PaymentErrorCode {
    PAYMENT_NOT_FOUND,
    BOOKING_NOT_FOUND,
    BOOKING_NOT_PAYABLE,
    PAYMENT_ALREADY_EXISTS,
    PAYMENT_ACCESS_DENIED,
    PAYMENT_ALREADY_SUCCEEDED,
    PAYMENT_ALREADY_FAILED,
    WEBHOOK_ALREADY_PROCESSED,
    WEBHOOK_UNSUPPORTED_STATUS,
    WEBHOOK_INVALID_AMOUNT,
    IDEMPOTENCY_KEY_REQUIRED,
    BOOKING_SERVICE_UNAVAILABLE
}
