server:
  port: 8081

spring:
  application:
    name: event-service

  datasource:
    url: jdbc:postgresql://localhost:5434/event_db
    username: event_user
    password: event_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: localhost:9092,localhost:9094,localhost:9096

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

logging:
  level:
    com.reyzarium.eventforge.eventservice: DEBUG