package com.reyzarium.eventforge.bookingservice.common.error;

public enum BookingErrorCode {
    BOOKING_NOT_FOUND,
    BOOKING_ACCESS_DENIED,
    EVENT_NOT_AVAILABLE,
    TICKET_TYPE_NOT_AVAILABLE,
    INSUFFICIENT_TICKETS,
    BOOKING_ALREADY_CONFIRMED,
    BOOKING_ALREADY_EXPIRED,
    BOOKING_INVALID_STATUS,
    IDEMPOTENCY_KEY_REQUIRED,
    INVALID_BOOKING_QUANTITY,
    EVENT_SERVICE_UNAVAILABLE
}
